// Generated by CoffeeScript 1.6.3
(function() {
  var BaseWriter;

  BaseWriter = (function() {
    function BaseWriter() {}

    BaseWriter.FORMAT_VERSION = 0;

    BaseWriter.BOUNSCALE_OPEN_UUID = "b74e646e-7e55-448f-814d-e36eedc44ea9";

    BaseWriter.BOUNSCALE_CLOSE_UUID = "4a061908-db52-4224-ad4b-9850a47c7edf";

    BaseWriter.strip_uuid = function(str) {
      return str.replace(BaseWriter.BOUNSCALE_OPEN_UUID, "").replace(BaseWriter.BOUNSCALE_CLOSE_UUID, "");
    };

    BaseWriter.prototype.write = function(collector_instances) {
      var collector, result, str, _i, _len, _ref;
      result = {
        'format_ver': BaseWriter.FORMAT_VERSION,
        'datetime': (new Date()).toString(),
        'data': []
      };
      result['framework_ver'] = "node.js " + (typeof global !== "undefined" && global !== null ? (_ref = global.process) != null ? _ref.version : void 0 : void 0);
      for (_i = 0, _len = collector_instances.length; _i < _len; _i++) {
        collector = collector_instances[_i];
        result['data'].push({
          'name': collector.name(),
          'value': collector.value()
        });
      }
      str = "" + BaseWriter.BOUNSCALE_OPEN_UUID + (JSON.stringify(result)) + BaseWriter.BOUNSCALE_CLOSE_UUID;
      this.output(str);
      return str;
    };

    BaseWriter.prototype.output = function(str) {};

    return BaseWriter;

  })();

  module.exports = BaseWriter;

}).call(this);
