// Generated by CoffeeScript 1.6.3
(function() {
  var BaseCollector;

  BaseCollector = (function() {
    function BaseCollector() {}

    BaseCollector.prototype.pre = function() {};

    BaseCollector.prototype.post = function() {};

    return BaseCollector;

  })();

  module.exports = BaseCollector;

}).call(this);
