// Generated by CoffeeScript 1.6.3
(function() {
  var BusynessCollector, CpuCollector, HerokuWriter, MemoryCollector, ThroughputCollector;

  BusynessCollector = require('./busyness_collector');

  ThroughputCollector = require('./throughput_collector');

  CpuCollector = require('./cpu_collector');

  MemoryCollector = require('./memory_collector');

  HerokuWriter = require('./heroku_writer');

  module.exports = function(req, res, next) {
    var collector, collector_instances, writer, _i, _j, _len, _len1;
    collector_instances = [new BusynessCollector(), new ThroughputCollector(), new CpuCollector(), new MemoryCollector()];
    for (_i = 0, _len = collector_instances.length; _i < _len; _i++) {
      collector = collector_instances[_i];
      collector.pre();
    }
    next();
    for (_j = 0, _len1 = collector_instances.length; _j < _len1; _j++) {
      collector = collector_instances[_j];
      collector.post();
    }
    writer = new HerokuWriter();
    return writer.write(collector_instances);
  };

}).call(this);
