// Generated by CoffeeScript 1.6.3
(function() {
  var BaseWriter, HerokuWriter, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseWriter = require('./base_writer');

  HerokuWriter = (function(_super) {
    __extends(HerokuWriter, _super);

    function HerokuWriter() {
      _ref = HerokuWriter.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    HerokuWriter.prototype.output = function(str) {
      return console.log(str);
    };

    return HerokuWriter;

  })(BaseWriter);

  module.exports = HerokuWriter;

}).call(this);
