// Generated by CoffeeScript 1.6.3
(function() {
  var BaseCollector, MemoryCollector, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseCollector = require('./base_collector');

  MemoryCollector = (function(_super) {
    __extends(MemoryCollector, _super);

    function MemoryCollector() {
      _ref = MemoryCollector.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    MemoryCollector.prototype.pre = function() {};

    MemoryCollector.prototype.post = function() {
      return this.post_memory = process.memoryUsage().rss / 1024 / 1024;
    };

    MemoryCollector.prototype.name = function() {
      return "memory";
    };

    MemoryCollector.prototype.value = function() {
      return this.post_memory;
    };

    return MemoryCollector;

  })(BaseCollector);

  module.exports = MemoryCollector;

}).call(this);
