// Generated by CoffeeScript 1.6.3
(function() {
  var BusynessCollector, ThroughputCollector, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BusynessCollector = require('./busyness_collector');

  ThroughputCollector = (function(_super) {
    __extends(ThroughputCollector, _super);

    function ThroughputCollector() {
      _ref = ThroughputCollector.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    ThroughputCollector.prototype.pre = function() {};

    ThroughputCollector.prototype.post = function() {};

    ThroughputCollector.prototype.name = function() {
      return "throughput";
    };

    ThroughputCollector.prototype.value = function() {
      if (BusynessCollector.history.length < 2) {
        return 0;
      } else {
        return (BusynessCollector.history.length / this.whole_sec()) * 60;
      }
    };

    return ThroughputCollector;

  })(BusynessCollector);

  module.exports = ThroughputCollector;

}).call(this);
